name: aegis_lights
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - black==25.11.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cityflow==0.1
      - click==8.3.1
      - contourpy==1.3.2
      - coverage==7.12.0
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - idna==3.11
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.5.0
      - pluggy==1.6.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==9.0.1
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - pytokens==0.3.0
      - pytz==2025.2
      - requests==2.32.5
      - six==1.17.0
      - tomli==2.3.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
prefix: /home/prab/miniconda3/envs/aegis_lights
